guiziweb_grid_assistant_admin:
    resource: "@GuiziwebSyliusGridAssistantPlugin/config/routes/admin.yaml"

guiziweb_grid_assistant_shop:
    resource: "@GuiziwebSyliusGridAssistantPlugin/config/routes/shop.yaml"
