on:
    push:
        branches: [main]

jobs:
    update-flex-endpoint:
        uses: symfony/recipes/.github/workflows/callable-flex-update.yml@main
        with:
            contrib: true
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}
